workflows:
  android-debug:
    name: FrameAI Android Debug
    working_directory: frameai_app
    max_build_duration: 60
    environment:
      groups:
        - common
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Compile OS Launcher Icons
        script: dart run flutter_launcher_icons
      - name: Build APK
        script: flutter build apk --debug --dart-define=GEMINI_API_KEY=$GEMINI_API_KEY
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
